CREATE TABLE User (
	Id INTEGER PRIMARY KEY,
	Name VARCHAR NOT NULL,
	LastName VARCHAR NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Birthday DATE NOT NULL,
    Gender INTEGER
);

CREATE TABLE Address (
	Id INTEGER PRIMARY KEY,
    UserId INTEGER NOT NULL,
    Street VARCHAR NOT NULL, 
    Number INT NOT NULL, 
    District VARCHAR NOT NULL, 
    City VARCHAR NOT NULL, 
    State VARCHAR NOT NULL, 
    AddressComplement VARCHAR,
    CEP VARCHAR(8) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES User (Id),
);